// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type League struct {
	Round     int32
	Active    bool
	StartedAt pgtype.Timestamptz
}

type Pairing struct {
	Round     int32
	PlayerId1 string
	PlayerId2 string
	Wins1     int32
	Wins2     int32
	Draws     int32
}

type Player struct {
	ID            string
	WildCardCount int32
	WildPackCount int32
}

type PlayerCardPool struct {
	PlayerID        string
	Name            string
	SetCode         string
	CollectorNumber int32
	Count           int32
}
